In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [8]:
b = np.array([[10,20,30],[60,70,80]])
print(b)

[[10 20 30]
 [60 70 80]]


In [9]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [10]:
print(a.ndim)
print(a.shape)

1
(5,)


In [11]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [14]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a = np.random.random((2,2))
print(a)

[[0.52658527 0.08209986]
 [0.48021161 0.17914091]]


In [16]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [18]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [19]:
a = np.array(np.arange(29)).reshape((5,6))
print(a)

ValueError: cannot reshape array of size 29 into shape (5,6)

In [22]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b=a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [23]:
b=a[0, :]
print(b)

[1 2 3]


In [24]:
b=a[:, 1]
print(b)

[2 5]


In [25]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2,1],[1,0]]
print(b)

[8 4]


In [26]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [27]:
b = x + y
print(b)

[5 7 9]


In [28]:
b = x - y
print(b)

[-3 -3 -3]


In [29]:
b = b * x
print(b)

[-3 -6 -9]


In [30]:
b = b / x
print(b)

[-3. -3. -3.]


In [31]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]
